version: '3'
services:
   web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ./app:/code
    environment:
      - FLASK_ENV=development

redis:
    image: "redis:alpine"
  