version: "3.9"

services:
  mysql:
    image: mysql:5.7
    networks:
      - twotier
    volumes:
      - type: bind
        source: ./mysql-data
        target: /var/lib/mysql
      - type: bind
        source: ./message.sql
        target: /docker-entrypoint-initdb.d/message.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost","-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 3


  flask-app:
    build: .
    networks:
      - twotier
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
        
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: devops

networks:
  twotier:
    driver: bridge

